version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
    - master
environment:
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  deploy_server:
    secure: q706iWwM10zvcjRbqItSEu+HLTX/qJnpDfK3ywcWoyfL6qOLejFH6xbm6u2D0v/4D/MXwMsubDv0sJstTjFk9kSqVewyDg1VEK+jK5Xr0CE=
  deploy_website:
    secure: o1tcoGCP0zw5GbDXcxws3JKx8VtPO1guVcF93yySiMc=
  db_server:
    secure: K3tw1JJQqsF0zSckjLdOJg==
  db_name:
    secure: brW8T5uSR6U3FKhXPrQJ3w==
  db_username:
    secure: fViNusck/3ewKyAw1iVOVQ==
  db_password:
    secure: 4y9U8rtIudL2GAfDA3JfbQ==
  jwt_secret:
    secure: M+XNGZRp9MtgE0JL5vqreHbaN2zGo6Md40OU9kyv6sjXxyRfmQkMfYYVmKId4RPR
install:
  - ps: >-
      $file = "./Backend/Api/appsettings.Production.json";
      (Get-Content $file).Replace("{db_server}", $env:db_server).Replace("{db_name}", $env:db_name).Replace("{db_username}", $env:db_username).Replace("{db_password}", $env:db_password).Replace("{jwt_secret}", $env:jwt_secret) | Set-Content $file
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Backend/Api.sln --verbosity m
  - npm install --global yarn
  - cd Frontend
  - yarn install
  - yarn run test-ci
  - yarn run build
  - cd ..
  - ps: >-
      Copy-Item -Path "./Frontend/build" -Destination "./Backend/Api/ClientApp/build" -Recurse
build:
  project: ./Backend/Api.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - cmd: dotnet publish --framework net5.0 --self-contained true -r win-x64 Backend\Api --output %appveyor_build_folder%\dist
artifacts:
  - path: dist
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;
    server: $(deploy_server)
    website: $(deploy_website)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
