version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
environment:
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  DefaultConnection-Web.config Connection String: 
    secure: XCd88qxQ5JDVfoGcLQeYQWrGCU6u6B3IXhiH9F16yEkP5FfTLoWEup0h3mer2aJEMQ3v3eNLGNoG1bGa6EE+gF5ivVxkL4ekjni2H+qCAsOJVQasYy1mhFIqoW7nMtp3FJFhhv8SLhi9Z7xF2updx+Qrmy3d57ZRIi3LQ6p2DmI=
  deploy_server_test:
    secure: qbUfDe0ngl5+/7mkQxs8ByxZ6QB93c59/494w4lEpOai3cgh5bDAiRBRYeOt7hQQ7JkG1kD6wV2IigmoKDvZHD4lsSg4IrSwWOWLSPJCyCI=
  deploy_website_test:
    secure: L4aPGohGkV1xWMMxniWVZryvAIvbB4zCKIDM5WvUh9k=
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Backend/Api.sln --verbosity m
build:
  project: ./Backend/Api.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - cmd: dotnet publish --framework netcoreapp3.1 Backend\Api --output %appveyor_build_folder%\dist
artifacts:
  - path: dist      
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;
    server: $(deploy_server_test)
    website: $(deploy_website_test)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false