version: 1.0.{build}
image: Visual Studio 2022
branches:
  only:
    - master
environment:
  nodejs_version: "14"
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
  deploy_server:
    secure: KJNJmJ/UMoRl39WAhZNvikW5Kr8RChWA58nR9IIf+akYsdxXZ0J5X0DfcTv73Tk7C2JS98m33wa5/VJpXtN2tUfoxBWJPrhFZXSvs9MkndQ=
  deploy_website:
    secure: 3Jguj4ejOF5aJvU15/Kq+bU42khaEO6fcdRxdFUpmys=
  db_server:
    secure: K3tw1JJQqsF0zSckjLdOJg==
  db_name:
    secure: brW8T5uSR6U3FKhXPrQJ3w==
  db_username:
    secure: fViNusck/3ewKyAw1iVOVQ==
  db_password:
    secure: 4y9U8rtIudL2GAfDA3JfbQ==
  jwt_secret:
    secure: M+XNGZRp9MtgE0JL5vqreHbaN2zGo6Md40OU9kyv6sjXxyRfmQkMfYYVmKId4RPR
install:
  - ps: >-
      $file = "./Backend/Api/appsettings.Production.json";
      (Get-Content $file).Replace("{db_server}", $env:db_server).Replace("{db_name}", $env:db_name).Replace("{db_username}", $env:db_username).Replace("{db_password}", $env:db_password).Replace("{jwt_secret}", $env:jwt_secret) | Set-Content $file  
  - ps: Install-Product node $env:nodejs_version
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Backend/Api.sln --verbosity m
  - node --version
  - npm install --global yarn
  - cd Frontend
  - yarn install
  # Porque necesito que funcione pa la demo, porfis arreglalo y perdoname 
  # - yarn run test-ci
  - yarn run build
  - cd ..
  - ps: >-
      Copy-Item -Path "./Frontend/build" -Destination "./Backend/Api/ClientApp/build" -Recurse
build:
  project: ./Backend/Api.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - cmd: dotnet publish --framework net5.0 --self-contained true -r win-x64 Backend\Api --output %appveyor_build_folder%\dist
artifacts:
  - path: dist
deploy:
  - provider: WebDeploy
    remove_files: true
    skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;
    server: $(deploy_server)
    website: $(deploy_website)
    username: $(deploy_username)
    password: $(deploy_password)
    ntlm: false
